os: linux
dist: jammy
language: minimal

notifications:
  email:
    on_success: change
    on_failure: always

jobs:
  include:
  - stage: test
    name: "conda linux"
    os: linux
    dist: jammy
    env: TEST_PROFILE="proteus-conda"
    install:
      - git lfs pull
      - sudo apt-get update
      - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      - bash miniconda.sh -b -p $HOME/miniconda
      - source "$HOME/miniconda/etc/profile.d/conda.sh"
      - hash -r
      - conda config --set always_yes yes --set changeps1 no
      - conda update -q conda
      - conda info -a
      - conda env create -f environment-dev.yml
      - conda activate proteus-dev
      - PROTEUS_OPT="-g0 -O1" make develop-conda
    script:
      - export MPLBACKEND="AGG"
      - py.test -n 1 --forked -v proteus/tests --ignore proteus/tests/POD
    deploy:
      provider: script
      script: bash ./scripts/deploy.sh docs
      skip_cleanup: true
      on:
        branch: main
  - stage: test
    name: "conda osx"
    os: osx
    osx_image: xcode14.2
    env: TEST_PROFILE="proteus-conda-osx"
    install:
      - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      - bash miniconda.sh -b -p $HOME/miniconda
      - source "$HOME/miniconda/etc/profile.d/conda.sh"
      - hash -r
      - conda config --set always_yes yes --set changeps1 no
      - conda update -q conda
      - conda info -a
      - conda env create -f environment-dev.yml
      - conda activate proteus-dev
      - PROTEUS_OPT="-g0 -O1" make develop-conda
    script:
      - export MPLBACKEND="AGG"
      - git lfs install
      - git lfs pull
      - py.test -n 1 --forked -v proteus/tests --ignore proteus/tests/POD
