name: proteus-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - pip =24.0
  - compilers =1.7.0
  - make =4.3
  - setuptools =69.2.0
  - cython =3.0.9
  - daetk =1.0.1
  - hdf5 =1.14.3=*mpich*
  - h5py =3.10.0=*mpich*
  - metis =5.1.0
  - mpich =4.2.0
  - mpich-mpicc =4.2.0
  - mpich-mpicxx =4.2.0
  - numpy =1.26.4
  - openblas =0.3.26
  - parmetis =4.0.3
  - petsc4py =3.20.5
  - petsc =3.20.5
  - scorec =2.2.7
  - superlu =5.2.2
  - superlu_dist =8.2.1
  - triangle =1.6
  - pychrono =7.0.0
  - gmsh =4.12.2
  - matplotlib =3.8.3
  - mpi4py =3.1.5
  - pytables =3.9.2
  - pytest =8.1.1
  - pytest-cov =4.1.0
  - pytest-xdist =3.5.0
  - scipy =1.12.0
  - tetgen =1.6.0
  - ncurses =6.4.20240210
  - python =3.10.14
  - future =1.0.0
  - ipyparallel =8.7.0
  - pillow =10.2.0
  - xtensor-python = 0.27.0
  - git-lfs =3.5.1
  - eigen =3.4.0
  - zoltan =3.901
  - hypre =2.28.0
  - mumps-mpi =5.6.2
  - numexpr =2.9.0
  - ptscotch =7.0.4
  - scalapack =2.2.0
  - tbb =2021.11.0
  - zipp =3.17.0
  - parso =0.8.3
  - pycparser =2.21
  - ipython =8.22.2
  - decorator =5.1.1
  - cffi =1.16.0
  - sympy =1.12