name: petsc-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - pip =24.0
  - setuptools =73.0.1
  - make =4.4.1
  - cmake
  - cython =3.0.11
  - swig 
  - numpy =2.1.1
  - pybind11 
  - openblas =0.3.28
