name: proteus-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - pip =23.2.1
  - compilers =1.5.2
  - make =4.3
  - setuptools =68.0.0
  - cython =3.0.0
  - daetk =1.0.1
  - hdf5 =1.14.1=*mpich*
  - h5py =3.9.0=*mpich*
  - metis =5.1.1
  - mpich =4.1.1
  - mpich-mpicc =4.1.1
  - mpich-mpicxx =4.1.1
  - numpy =1.25.1
  - openblas =0.3.23
  - parmetis =4.0.3
  - petsc4py =3.19.2
  - petsc =3.19.3
  - scorec =2.2.7
  - superlu =5.2.2
  - superlu_dist =7.2.0
  - triangle =1.6
  - pychrono =7.0.0
  - gmsh =4.11.1
  - matplotlib =3.7.2
  - mpi4py =3.1.4
  - pytables =3.8.0
  - pytest =7.4.0
  - pytest-cov =4.1.0
  - pytest-xdist =3.3.1
  - scipy =1.11.1
  - tetgen =1.6.0
  - ncurses =6.4
  - python =3.10.12
  - future =0.18.3
  - ipyparallel =8.6.1
  - pillow =9.4.0
  - xtensor-python = 0.26.1
  - git-lfs =3.3.0
  - eigen
  - zoltan =3.901
  - hypre =2.28.0
  - mumps-mpi =5.2.1
  - numexpr =2.8.4
  - ptscotch =6.0.9
  - scalapack =2.2.0
  - tbb =2021.5.0
  - zipp =3.8.0
  - parso =0.8.3
  - pycparser =2.21
  - ipython =8.14.0
  - decorator =5.1.1
  - cffi =1.15.1
  - sympy =1.11.1