name: proteus-dev-up-240912
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pip
  - compilers
  - make
  - setuptools
  - cython
  - pybind11
  - hdf5 =*=mpi_*
  - h5py =*=mpi_*
  - metis
  - numpy
  - openblas >=0.3.20
  - parmetis
  - petsc4py
  - petsc
  - superlu
  - superlu_dist
  - scorec >=4.2.1
  - triangle
  - pychrono >=10.0.0
  - gmsh
  - matplotlib
  - mpi4py
  - pytest
  - pytest-cov
  - pytest-xdist
  - scipy
  - tetgen
  - ncurses
  - python
  - ipyparallel
  - xtensor-python
  - git-lfs
  - eigen
  - zoltan
  - hypre
  - tbb
  - zipp
  - parso
  - pycparser
  - ipython
  - decorator
  - cffi
  - jupyterlab
  - llvm-openmp
