name: proteus-dev-up-3
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - compilers
  - make
  - setuptools
  - cython
  - daetk
  - hdf5 =*=*mpich*
  - h5py =*=*mpich*
  - metis
  - mpich
  - mpich-mpicc
  - mpich-mpicxx
  - numpy
  - openblas
  - parmetis
  - petsc4py
  - petsc
  - scorec
  - superlu
  - superlu_dist
  - triangle
  - pychrono
  - gmsh
  - matplotlib
  - mpi4py
  - pytables
  - pytest
  - pytest-cov
  - pytest-xdist
  - scipy
  - tetgen
  - ncurses
  - python
  - future
  - ipyparallel
  - pillow
  - xtensor-python
  - git-lfs
  - eigen
  - zoltan
  - hypre
  - mumps-mpi
  - numexpr
  - ptscotch
  - scalapack
  - tbb
  - zipp
  - parso
  - pycparser
  - ipython
  - decorator
  - cffi
  - netcdf4
  - jupyterlab